# config.py

# DATA
NUM_FEATURES = 7
NUM_CLASSES = 4

# SPLIT
TEST_SIZE = 0.4
RANDOM_STATE = 42

# NOISE
GAUSSIAN_NOISE_STD = 0.18
UNIFORM_NOISE_RANGE = 0.15

# MODEL
LAYER1_UNITS = 10
LAYER2_UNITS = 8
DROPOUT_RATE = 0.35

# TRAINING
EPOCHS = 25
BATCH_SIZE = 16
PATIENCE = 3

# FILE PATHS
DATA_PATH = "dataset_4class.csv"
MODEL_TFLITE_PATH = "model.tflite"
MODEL_HEADER_PATH = "model.h"
SCALER_MEAN_PATH = "scaler_mean.npy"
SCALER_STD_PATH = "scaler_std.npy"